// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

MONO_EMBEDDINATOR_BEGIN_DECLS

typedef MonoEmbedObject Security_Resource;
typedef MonoEmbedObject Security_Encryption;
typedef MonoEmbedObject Security_EncryptionResult;
typedef MonoEmbedObject Security_Attribute;
typedef MonoEmbedObject Security_String;

MONO_EMBEDDINATOR_API Security_Resource* Security_Resource_new();

MONO_EMBEDDINATOR_API Security_Encryption* Security_Encryption_new();
MONO_EMBEDDINATOR_API const char* Security_Encryption_SHA256(const char* UrlToHash);
MONO_EMBEDDINATOR_API Security_EncryptionResult* Security_Encryption_Encrypt(const char* ToEncrypt, bool format);

MONO_EMBEDDINATOR_API Security_EncryptionResult* Security_EncryptionResult_new(const char* payload, const char* iv, const char* key);
MONO_EMBEDDINATOR_API const char* Security_EncryptionResult_get_Payload(Security_EncryptionResult* object);
MONO_EMBEDDINATOR_API void Security_EncryptionResult_set_Payload(Security_EncryptionResult* object, const char* value);
MONO_EMBEDDINATOR_API const char* Security_EncryptionResult_get_IV(Security_EncryptionResult* object);
MONO_EMBEDDINATOR_API void Security_EncryptionResult_set_IV(Security_EncryptionResult* object, const char* value);
MONO_EMBEDDINATOR_API const char* Security_EncryptionResult_get_Key(Security_EncryptionResult* object);
MONO_EMBEDDINATOR_API void Security_EncryptionResult_set_Key(Security_EncryptionResult* object, const char* value);

MONO_EMBEDDINATOR_API int32_t Security_String_get_app_name();
MONO_EMBEDDINATOR_API void Security_String_set_app_name(int32_t value);
MONO_EMBEDDINATOR_API int32_t Security_String_get_hello();
MONO_EMBEDDINATOR_API void Security_String_set_hello(int32_t value);

MONO_EMBEDDINATOR_END_DECLS
